# Generated by Django 3.1.3 on 2020-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('require_cal_coefficient_values', models.BooleanField(default=True)),
                ('require_cal_notes', models.BooleanField(default=False)),
                ('require_dep_sensor_uid', models.BooleanField(default=True)),
                ('require_dep_startDateTime', models.BooleanField(default=True)),
                ('require_dep_stopDateTime', models.BooleanField(default=True)),
                ('require_dep_lat', models.BooleanField(default=True)),
                ('require_dep_lon', models.BooleanField(default=True)),
                ('require_dep_mooring_uid', models.BooleanField(default=True)),
                ('require_dep_CUID_Deploy', models.BooleanField(default=True)),
                ('require_dep_node_uid', models.BooleanField(default=False)),
                ('require_dep_versionNumber', models.BooleanField(default=True)),
                ('require_dep_deployedBy', models.BooleanField(default=False)),
                ('require_dep_CUID_Recover', models.BooleanField(default=True)),
                ('require_dep_orbit', models.BooleanField(default=False)),
                ('require_dep_deployment_depth', models.BooleanField(default=True)),
                ('require_dep_water_depth', models.BooleanField(default=True)),
                ('require_dep_notes', models.BooleanField(default=False)),
                ('require_cruise_ship_name', models.BooleanField(default=True)),
                ('require_cruise_cruise_state_date', models.BooleanField(default=True)),
                ('require_cruise_cruise_end_date', models.BooleanField(default=True)),
                ('require_cruise_notes', models.BooleanField(default=True)),
                ('require_vessel_prefix', models.BooleanField(default=True)),
                ('require_vessel_vessel_designation', models.BooleanField(default=True)),
                ('require_vessel_vessel_name', models.BooleanField(default=True)),
                ('require_vessel_ICES_code', models.BooleanField(default=True)),
                ('require_vessel_operator', models.BooleanField(default=True)),
                ('require_vessel_call_sign', models.BooleanField(default=True)),
                ('require_vessel_MMSI_number', models.BooleanField(default=True)),
                ('require_vessel_IMO_number', models.BooleanField(default=True)),
                ('require_vessel_length', models.BooleanField(default=True)),
                ('require_vessel_max_speed', models.BooleanField(default=True)),
                ('require_vessel_max_draft', models.BooleanField(default=True)),
                ('require_vessel_designation', models.BooleanField(default=True)),
                ('require_vessel_active', models.BooleanField(default=True)),
                ('require_vessel_R2R', models.BooleanField(default=True)),
            ],
        ),
    ]
