# Generated by Django 3.1.3 on 2020-11-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_cal_coefficient_values',
            new_name='require_calibration_coefficient_values',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_cal_notes',
            new_name='require_calibration_notes',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_CUID_Deploy',
            new_name='require_deployment_CUID_Deploy',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_CUID_Recover',
            new_name='require_deployment_CUID_Recover',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_deployedBy',
            new_name='require_deployment_deployedBy',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_deployment_depth',
            new_name='require_deployment_deployment_depth',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_lat',
            new_name='require_deployment_lat',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_lon',
            new_name='require_deployment_lon',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_mooring_uid',
            new_name='require_deployment_mooring_uid',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_node_uid',
            new_name='require_deployment_node_uid',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_notes',
            new_name='require_deployment_notes',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_orbit',
            new_name='require_deployment_orbit',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_sensor_uid',
            new_name='require_deployment_sensor_uid',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_startDateTime',
            new_name='require_deployment_startDateTime',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_stopDateTime',
            new_name='require_deployment_stopDateTime',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_versionNumber',
            new_name='require_deployment_versionNumber',
        ),
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_dep_water_depth',
            new_name='require_deployment_water_depth',
        ),
    ]
