# Generated by Django 3.1.3 on 2020-11-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0002_auto_20201123_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_cruise_cruise_state_date',
            new_name='require_cruise_cruise_start_date',
        ),
    ]
